changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - feature
    - title: Bugfixes
      labels:
        - bugfix
    - title: Other Changes
      labels:
        - "*"
