# REST API.
api:
    listen: 8080
    authentication: $2a$10$gjcw/lDaKwV.Bms2Zfo44ubCD6443i64su.la.ZHfUFC4qos5xpRG

# Network interface for ethernet connection.
# Remove or set to "" to disable ethernet configuration by controller.
ethernet: "eth0"

# Directories for configuration and temporary files.
directories:
    config: "test_config"
    tmp: "/var/cache/lightbull"

leds:
    parts:
        - name: "horn_left"
          leds: [[0, 68], ]
        - name: "head_left"
          leds: [[69, 156], [199, 249]]
        - name: "hole_left"
          leds: [[157, 198], ]
        - name: "head_right"
          leds: [[250, 392], ]
        - name: "horn_right"
          leds: [[400, 468], ]
    brightnessCap: 80
    spiMHz: 1
    fps: 25
    drawDummy: false
