name: Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install go
      uses: actions/setup-go@v1
    - name: Build go
      run: make
