name: Build
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'
    - name: Build go
      run: make
    - name: Get the version
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
    - name: Print version
      run: echo ${{ steps.get_version.outputs.version }}
